services:
  - type: web
    name: veripura-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile

    envVars:
      - key: ENVIRONMENT
        value: production

      - key: DEBUG
        value: false

      - key: QR_BASE_URL
        value: https://veripura-system.onrender.com

      - key: TESSERACT_CMD
        value: tesseract

      - key: CORS_ORIGINS
        value: '["https://veripura-system.vercel.app","https://veripura-system.onrender.com"]'

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: JWT_ALGORITHM
        value: HS256

      - key: JWT_EXPIRE_MINUTES
        value: "1440"
